# Generated by Django 2.2.16 on 2020-10-19 03:04

import demo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('result', models.ForeignKey(default=demo.models.get_default_action_result, on_delete=django.db.models.deletion.CASCADE, to='demo.ActionResult')),
                ('status', models.ForeignKey(default=demo.models.get_default_action_status, on_delete=django.db.models.deletion.CASCADE, to='demo.ActionStatus')),
            ],
        ),
    ]
